name: My First workflow

on: [push]

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome come message
              run: echo "My first github Action job"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md